### ISSUE TITLE
Graph ASCII style

### ISSUE THREAD

**Issue by madjestic** [miguelmota/cointop#102]
Hey guys,

After installing the cointop from (go) sources, I see the graph as a bunch of ASCII rectangles, which is different from what I see on in the repo pics.  Is there a way to change it, or maybe I am missing some fonts on my side?

![image](https://user-images.githubusercontent.com/3270083/113502553-49d9a780-952d-11eb-96f8-bbaeb869ceb1.png)

Thanks,
Vlad

**Comment by miguelmota** [comment]
Hi @madjestic, what OS are you on? The [FAQ](https://docs.cointop.sh/faq/) might offer additional help as well. Most likely it's a font issue and you'll need to change to a font that supports 'braille' dots. You can try [Iosevka](https://github.com/be5invis/Iosevka), [DejaVu](https://dejavu-fonts.github.io/) or Symbola font. If using Arch install `ttf-ubraille`

**Comment by madjestic** [comment]
Hey, I am running:
```shell
$ uname -a
Linux nu 5.4.80-gentoo-r1 #5 SMP PREEMPT Mon Jan 18 11:18:39 CET 2021 x86_64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz GenuineIntel GNU/Linux
```
![image](https://user-images.githubusercontent.com/3270083/113522813-f9e9f780-95a3-11eb-8ed1-0f77b62ec17b.png)

As you can see, I am running DejaVu Sans Mono font.  I don't think that `ttf-ubraille` exists for gentoo...

**Comment by miguelmota** [comment]
@madjestic thanks for the additional info. Since the terminal is `urxvt` then I suspect it's a configuration problem.

You can try setting `URxvt.letterSpace: 1` in `.Xresources` or `~/.Xdefaults` ([source](https://github.com/powerline/fonts/issues/176#issuecomment-240252912))

If that didn't work, you can try setting fallback fonts.
For example, `URxvt.font: xft:DejaVu Sans:pixelsize=14,xft:Symbola,xft:Noto Emoji:minspace=False` ([source](https://github.com/powerline/fonts/issues/176#issuecomment-370198936))

Before:

![DeepinScreenshot_select-area_20210404212529](https://user-images.githubusercontent.com/168240/113537086-8ab4d900-958c-11eb-8bff-50951330cf09.png)

After:

![DeepinScreenshot_select-area_20210404212602](https://user-images.githubusercontent.com/168240/113537105-943e4100-958c-11eb-84f6-5c8b5734de57.png)

`~/.Xresources`

![DeepinScreenshot_select-area_20210404212624](https://user-images.githubusercontent.com/168240/113537117-9accb880-958c-11eb-817e-75547f6898d9.png)

**Comment by madjestic** [comment]
@miguelmota Thanks for great tips!  Unfortunately, the fix suggestions in regards to tweaking Urxvt did not quite work or resulted in other issues, however I tried running cointop using `xterm` and that worked ok.  I think that is an acceptable workaround.


Thanks,
Vlad

**Comment by miguelmota** [comment]
@madjestic ah ok, I'm sure if you keep tweaking settings it'll eventually work but xterm is also a great terminal. Cheers!
