### ISSUE TITLE
Show X axis labels on charts

### ISSUE THREAD

**Issue by simon-anz** [miguelmota/cointop#156]
It would be nice if the X axis of the charts had (short) labels describing some of the intervals shown (days, weeks, etc)

**Comment by miguelmota** [comment]
Currently cointop uses the [termui](https://github.com/gizak/termui) library for chart, and the library doesn't provide a way to easily use dates as x-axis. I'm sure there's a better library out there but haven't found it yet

Related https://github.com/miguelmota/cointop/issues/134

**Comment by simon-anz** [comment]
We may have to pre-format the dates as strings?  The problem at the moment is that the date-axis data is discarded before rendering (which indirectly causes the issues with time-series that don't line up - see #157 )

**Comment by simon-anz** [comment]
In fact, it looks like the plot.DataLabels doesn't actually do anything in termui yet

**Comment by miguelmota** [comment]
termui did a big v3 release not too long ago which had breaking changes so cointop still uses [v2](https://github.com/gizak/termui/tree/v2) of termui which does have ability to add X axis labels (termui is forked into cointop [here](https://github.com/miguelmota/cointop/tree/master/pkg/termui))

The axis labels can be added here in [chartplot](https://github.com/miguelmota/cointop/blob/master/pkg/chartplot/chartplot.go#L19) subpackage

```go
t.DataLabels = []string{"a", "b", "c"}
```

The timestamp for chart points can be retrieved [here](https://github.com/miguelmota/cointop/blob/5f76e89a0be481796fe1c33bc75beb4966c6fbe1/cointop/chart.go#L161) to generate axis labels 

for example

```go
for i := range sorted {
  price := sorted[i][1]
  timestamp := sorted[i][0]
  data = append(data, price)
  axisLabel := time.UnixMilli(int64(timestamp)).Format("2006-01-02 15:04:05")
  ...
}
```

The x-axis layout might need some tweaking in termui fork [linechart.go](https://github.com/miguelmota/cointop/blob/5f76e89a0be481796fe1c33bc75beb4966c6fbe1/pkg/termui/linechart.go#L189) because it doesn't seem to auto-adjust

hope this helps!

**Comment by simon-anz** [comment]
I can't quite figure out how to use the library - suspect it's something to do with the chart data being resampled in interpolateData() and how that means the number of data elements now no longer aligns with the number of labels passed.

It sortof works if I disable interpolation, but the graph gets wider/narrower depending on the amount of data from backend. 

Might need to combine it with my resample elsewhere, and remove graph interpolation.
![Screen Shot 2021-09-18 at 3 16 55 pm](https://user-images.githubusercontent.com/69175652/133873642-8bec8085-b568-4b7a-97df-00bfc762795a.png)

**Comment by lyricnz** [comment]
OK, working pretty well here (now that data is resampled, and additional interpolation is removed). Need to decide on date-time format for different ranges (adaptive - to keep them short and relevant). How's this???

- <24h: 15:03
- <7d: Fri 15:03
- <1Y: 31-Aug
- else: Aug 2017

Examples attached below.  Are there locale issues that we need to consider here?

![Screen Shot 2021-09-27 at 8 05 57 am](https://user-images.githubusercontent.com/122371/134825754-a3444a17-723d-44cc-a854-7e33869742b3.png)

![Screen Shot 2021-09-27 at 8 05 52 am](https://user-images.githubusercontent.com/122371/134825762-f173c624-446a-4335-a2c6-bd012c975298.png)

![Screen Shot 2021-09-27 at 8 05 39 am](https://user-images.githubusercontent.com/122371/134825765-92713ce5-b3ef-4113-96b1-cd2f38c765df.png)

![Screen Shot 2021-09-27 at 8 05 30 am](https://user-images.githubusercontent.com/122371/134825769-dc1b38e1-27c9-49ee-8a91-142959a74174.png)
