### ISSUE TITLE
Charts with insufficient data present misleading view

### ISSUE THREAD

**Issue by simon-anz** [miguelmota/cointop#163]
When viewing a coin on a timeframe longer than data available (eg GTC on 180D timeframe), the chart shows the data available as filling the entire X axis (time), when in fact it is less.  This is non-apparent because there is neither X-axis labels, or a gap to the left where the data was not available.

Both of these are raised already, this issue 
#156 Show X axis labels on charts
#157 Why does graph sometimes show a steep downturn on the right hand side of chart?

Perhaps the chart should show disjoint or non-continuous line in this case?

Eg gitcoin only has data since 25/May see https://www.coingecko.com/en/coins/gitcoin but 6M chart (theoretically back to 6 March) looks like this:

![Screen Shot 2021-09-06 at 8 35 55 am](https://user-images.githubusercontent.com/69175652/132143209-a96e12bb-0719-4ccb-b259-06600acbbe5a.png)

The same thing happens on portfolio view, but because it's added up, it causes other strange behaviour.

**Comment by blockjoe** [comment]
I have a pull request out for taking care of this in the portfolio case: #159, which is instead of iterating forward and appending to the y data on the chart, instead initialize the y data on the chart to the longest length and iterate backwards for summing the data.

Keeping around all X labels is likely going to be difficult; I know that dynamic date axis formatting even in rich graphical libraries is always fickle. Maybe have an X-axis label for the first and last point of the chart would be able to convey this issue? Another thought is maybe something in the top status bar showing the first and last timestamp of the chart data to avoid having to deal with date axis formatting all together.

While I like the idea of zero-ing out unavailable data, I realized that the coinbase app UX is identical to cointop's in this case (except you get the X value of the data by hovering over the chart). That makes me realize that trying to predict and correct behavior from an external API and conditionally fill with 0 data is likely going to be hard, even harder when supporting more than one source.

**Comment by simon-anz** [comment]
The low-level API doesn't return bad data, it just returns it for the subset of time that it has available.  No need to "guess" where it belongs - every data point has a timestamp and a value (just cointop throws away the timestamp too early).

**Comment by simon-anz** [comment]
The patch in #165 fixes this (for portfolio only, currently) by resampling the data across the requested time period
![Screen Shot 2021-09-18 at 10 34 51 am](https://user-images.githubusercontent.com/69175652/133865987-15abd333-23a3-4d9e-92ed-0bb6f19c9819.png)

**Comment by simon-anz** [comment]
Added resample for the main chart to the PR. Thoughts?
![Screen Shot 2021-09-18 at 10 58 22 am](https://user-images.githubusercontent.com/69175652/133866837-2693adb8-213f-4840-8de4-c8a1b6d5ee74.png)

**Comment by lyricnz** [comment]
I feel this is solved by resampling. Certainly the "misleading" part of the subject.  Possibly, if we have x-axis labels, and the available data is less than the requested window, we could show just the data (with full width) and accurate x-labels.  But that's enhancement/future.
