### ISSUE TITLE
"Synthetix" name problem

### ISSUE THREAD

**Issue by mrlogick** [miguelmota/cointop#81]
I cannot find the exact name, i already tried:
```
cointop price -c "synthetix"
cointop price -c "Synthetix"
cointop price -c "SynthetixNetworkToken"
cointop price -c "Synthetix Network Token"
```
Where can I find the exact names of the coins?
Is there a way to write the "SNX" (for Synthetix) or "BTC" (for Bitcoin)?

**Comment by miguelmota** [comment]
@mrlogick it looks like coingecko is using the previous name of synthetix which was "havven"  as the id (according to their api [coins/list](https://www.coingecko.com/en/api#explore-api)

![Screenshot from 2021-01-31 20-43-16](https://user-images.githubusercontent.com/168240/106415924-2303d580-6405-11eb-9f2f-3c8dec58d5da.png)

```bash
$ cointop price -c "havven"
$17.24
```

The coingecko price api requires the id. I agree that it's not intuitive at all and cointop should be smarter about using coin names and symbols. Will get this fixed in a future release.

Thanks for the report!

**Comment by mrlogick** [comment]
Thanks man. Just to point out: "Binance Coin" has the id "binancecoin" without spaces.

**Comment by miguelmota** [comment]
Fix for improved lookup by coin name or symbol is now on main branch.

```bash
$ cointop price -c synthetix
$26.47
$ cointop price -c snx
$26.47
$ cointop price -c "Synthetix Network Token"
$26.47
$ cointop price -c binance
$124.87
$ cointop  price -c bnb
$124.87
$cointop  price -c "Binance Coin"
$124.63
```

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/a9473e354c480d3bd91c269902449f21ae38f6b3
