### ISSUE TITLE
"snap run cointop" returns error connecting to host and wont start application 

### ISSUE THREAD

**Issue by daronadidas** [miguelmota/cointop#88]
When I run the command to start via terminal it responds... "dial tcp: lookup graphs2.coinmarketcap.com: no such host"

I can find the cointop folder created when I run the start command but the folders created withing are empty.. was thinking I could find .config file and edit but no such luck. 

Running cointop on Raspberry pi4 loaded with ubuntu. 

"snap run cointop" is command used.

Thanks!

![iPhone_19603_IMG_0648](https://user-images.githubusercontent.com/66711479/107897539-ece34d00-6efe-11eb-92cf-dfa7748663e4.jpg)

**Comment by miguelmota** [comment]
Related: https://github.com/miguelmota/cointop/issues/74

CoinMarketCap changed the graphs endpoint and hasn't been updated yet which explains the fetch error. However cointop should still show the coins table so this might be an internet connection issue? 

This is what I'm seeing; the 'not enough data for chart' error is expected because the graphs endpoint is currently broken, but cointop should still render the table.

```bash
snap run cointop --api coinmarketcap
```

![Screenshot from 2021-02-14 23-01-14](https://user-images.githubusercontent.com/168240/107915062-8d923680-6f18-11eb-9feb-3453a19b1125.png)

**Comment by daronadidas** [comment]
Thanks for the quick response!

"snap run cointop --api coinmarketcap" AND "snap run cointop --api coingecko" both return the same original message as shown in the previously attached image

internet connection is good - I have browser and ssh capabilites: "ssh cointop.sh" works

Thanks!

**Comment by miguelmota** [comment]
Thanks for checking! sounds like it's an internal bug with cointop

**Comment by miguelmota** [comment]
CoinMarketCap graphs endpoint has been updated on main branch. Chart should render now.

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/295f163ae24e8bde849f72bfdf7b604234b4691e
